#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d II VII VIII IX X
bspc monitor DP-4 -d I III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#689d6a
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Galculator state=floating
bspc rule -a scrcpy state=floating
bspc rule -a osu\! state=fullscreen
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=pseudo_tiled
#bspc rule -a TelegramDesktop state=pseudo_tiled
polybar topbar & polybar topbar1 &
